travis:
  secure:
    BINSTAR_TOKEN: ctkPho2UyiwIwxoR7SuWaNmKRutBorm3p+dW2yFbuR9ozjLNRKt+OmjGWSoCaoOxKYkUpoaM+rEdnAEo+gl6FxBfNQ+nAkrS/9MUrqyyw4r1ztm5bdHdO0mQGJ9F8jJTyPhtlWKBhesIARdUVFkHmWX4ghx3lV3HPY4T5fMVfCCOtIDr5mZsGWDGdKqwVgNxN+59y4T9fWXg+Jl+g0Mdu8AtJf1/rd1v2m0rOzqPldinRi/ks8wUmC/XzlYRdw40GeExW6ENO7oF4ocaH6XEZcyu5mtvIvYDzCRuASHLQvq5e49AycgWDsOT8++MpOpLbNO/34AS1TpouLyu6lcPewXw5YK1JQf+SCKWjp3LzJZ+eadm865clcw9r8J97tqJS1qTTOuhcWSOjCqOgRg4WY7IU03j1jmyUVswFYpuYGS7HdvG0WjFhyMNXCSlYhjH0u8VECP1j7+t9kaKATwGUt5dCaC4lXdVVoAYyK66y7vFb5tQGSJX/U7iLSY+2lhjr8AoemlZy4R1+N05PbFjPvrtxaCI4x+Zp0hivH+EzaX76YTuBvtetdEK3diN5i/fejSlnyfQI4b489TVkV5yCwX6QVuO1wxOkLsjgMp7KuTdUSvRNZ3At4cL3ZWD/xGozeVjyJ8VVxeKkvrmWcVLsr9fHYL9zh39s5Vw9RsL8kE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
